**25.1<br>Run the Floyd-Warshall algorithm on the weighted, directed graph of Figure 25.2. Show the matrix $D^{(k)}$ that results for each iteration of the outer loop.**

In [25]:
def floyd_warshall(W):
    n=len(W)
    # D is a collection of D(i), i=0,1,2,...,k
    D=[W] # D(i) is a list of n*n matrices.
    for k in range(n):
        # generate an empty n*n matrix D(k) for each k
        # append D(k) to D
        D.append(W)
        for i in range(n):
            for j in range(n):
                # modify the value of every cell dij in D(k)
                # according to optimal substructure
                D[k+1][i][j]=min(D[k][i][j],D[k][i][k]+D[k][k][j])
        print (D[k],'\n')
    # the final solution of dij is the last D(n) added to D
    return D[n]

In [26]:
W=[[0,10000,10000,10000,-1,10000],
  [1,0,10000,2,10000,10000],
  [10000,2,0,10000,10000,-8],
  [-4,10000,10000,0,3,10000],
  [10000,7,10000,10000,0,10000],
  [10000,5,10,10000,10000,0]]
floyd_warshall(W)

[[0, 10000, 10000, 10000, -1, 10000], [1, 0, 10000, 2, 0, 10000], [10000, 2, 0, 10000, 9999, -8], [-4, 9996, 9996, 0, -5, 9996], [10000, 7, 10000, 10000, 0, 10000], [10000, 5, 10, 10000, 9999, 0]] 

[[0, 10000, 10000, 10000, -1, 10000], [1, 0, 10000, 2, 0, 10000], [3, 2, 0, 4, 2, -8], [-4, 9996, 9996, 0, -5, 9996], [8, 7, 10000, 9, 0, 10000], [6, 5, 10, 7, 5, 0]] 

[[0, 10000, 10000, 10000, -1, 9992], [1, 0, 10000, 2, 0, 9992], [3, 2, 0, 4, 2, -8], [-4, 9996, 9996, 0, -5, 9988], [8, 7, 10000, 9, 0, 9992], [6, 5, 10, 7, 5, 0]] 

[[0, 10000, 10000, 10000, -1, 9992], [-2, 0, 9998, 2, -3, 9990], [0, 2, 0, 4, -1, -8], [-4, 9996, 9996, 0, -5, 9988], [5, 7, 10000, 9, 0, 9992], [3, 5, 10, 7, 2, 0]] 

[[0, 6, 9999, 8, -1, 9991], [-2, 0, 9997, 2, -3, 9989], [0, 2, 0, 4, -1, -8], [-4, 2, 9995, 0, -5, 9987], [5, 7, 10000, 9, 0, 9992], [3, 5, 10, 7, 2, 0]] 

[[0, 6, 9999, 8, -1, 9991], [-2, 0, 9997, 2, -3, 9989], [-5, -3, 0, -1, -6, -8], [-4, 2, 9995, 0, -5, 9987], [5, 7, 10000, 9, 0, 9992], [3, 5,

[[0, 6, 9999, 8, -1, 9991],
 [-2, 0, 9997, 2, -3, 9989],
 [-5, -3, 0, -1, -6, -8],
 [-4, 2, 9995, 0, -5, 9987],
 [5, 7, 10000, 9, 0, 9992],
 [3, 5, 10, 7, 2, 0]]

**25.2<br>Show how to compute the transitive closure using the technique of Section 25.1.**

In [27]:
#import numpy as np
def floyd_warshall_transitive_closure(W):
    n=len(W)
    # T is a collection of T(i), i=0,1,2,...,k
    T=[W]
    # define T0, which is a identity matrix + edges in W as 1
    for i in range(n):
        for j in range(n):
            if W[i][j]<10000:
                T[0][i][j]=1
            else:
                T[0][i][j]=0
    
    for k in range(n):
        # generate an empty n*n matrix T(k) for each k
        # append T(k) to T to work on
        T.append(W)
        
        for i in range(n):
            for j in range(n):
                # modify the value of every cell tij in T(k)
                # according to optimal substructure
                T[k+1][i][j]=(T[k][i][j] or (T[k][i][k] and T[k][k][j]))
        
    # the final solution of dij is the last T(n) added to T
    return T[n]

In [28]:
W=[[0,10000,10000,10000,-1,10000],
  [1,0,10000,2,10000,10000],
  [10000,2,0,10000,10000,-8],
  [-4,10000,10000,0,3,10000],
  [10000,7,10000,10000,0,10000],
  [10000,5,10,10000,10000,0]]
floyd_warshall_transitive_closure(W)

[[1, 1, 0, 1, 1, 0],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 1, 1, 1, 1],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 1, 1, 1, 1]]

**25.2-3<br>Modify the FLOYD-WARSHALL procedure to compute the $\Pi ^{(k)}$ matrices according to equations (25.6) and (25.7). Prove rigorously that for all $i\in V$, the predecessor subgraph $G_{\pi ,i}$ is a shortest path tree with root $i$. (*Hint*: To show that $G_{\pi ,i}$ is acyclic, first show that $\pi _{ij}^{(k)}=l$ implies $d_{ij}^{(k)} \geq d_{il}^{(k)}+w{ij}$, according to the definition of $\pi _{ij}^{(k)}$. Then, adapt the proof of Lemma 24.16.)**

In [29]:
import numpy as np
def floyd_warshall_predecessor_subgraph(W):
    
    n=len(W)
    # define D0
    D=[W]
    
    # define P0 according to equation 25.6
    P=[np.zeros((n,n))]
    for i in range(n):
        for j in range(n):
            if W[i][j]<10000 and W[i][j]!=0:
                P[0][i][j]=i
            else:
                P[0][i][j]=np.nan
    
    for k in range(n):
        # generate an empty n*n matrix for each k to work on
        P.append(np.zeros((n,n)))
        D.append(W)
        
        for i in range(n):
            for j in range(n):
                
                # assign value of P[k] according to equation 25.7
                if D[k+1][i][j]<=D[k][i][k]+D[k][k][j]:
                    P[k+1][i][j]=P[k][i][j]
                else:
                    P[k+1][i][j]=P[k][k][j]
                # modify the value of every cell dij in D(k)
                D[k+1][i][j]=min(D[k][i][j],D[k][i][k]+D[k][k][j])
                       
    # the final solution of P and D is the last matrice (n) 
    return P[n], D[n]

In [30]:
W=np.array([[0,10000,10000,10000,-1,10000],
  [1,0,10000,2,10000,10000],
  [10000,2,0,10000,10000,-8],
  [-4,10000,10000,0,3,10000],
  [10000,7,10000,10000,0,10000],
  [10000,5,10,10000,10000,0]])
floyd_warshall_predecessor_subgraph(W)

[[nan nan nan nan  0. nan]
 [ 1. nan nan  1. nan nan]
 [nan  2. nan nan nan  2.]
 [ 3. nan nan nan  3. nan]
 [nan  4. nan nan nan nan]
 [nan  5.  5. nan nan nan]] [[    0 10000 10000 10000    -1 10000]
 [    1     0 10000     2 10000 10000]
 [10000     2     0 10000 10000    -8]
 [   -4 10000 10000     0     3 10000]
 [10000     7 10000 10000     0 10000]
 [10000     5    10 10000 10000     0]]


(array([[nan,  4., nan,  1.,  0.,  2.],
        [ 3., nan, nan,  1.,  0.,  2.],
        [ 3.,  5., nan,  1.,  0.,  2.],
        [ 3.,  4., nan, nan,  0.,  2.],
        [ 3.,  4., nan,  1., nan,  2.],
        [ 3.,  5.,  5.,  1.,  0., nan]]),
 array([[    0,     6,  9999,     8,    -1,  9991],
        [   -2,     0,  9997,     2,    -3,  9989],
        [   -5,    -3,     0,    -1,    -6,    -8],
        [   -4,     2,  9995,     0,    -5,  9987],
        [    5,     7, 10000,     9,     0,  9992],
        [    3,     5,    10,     7,     2,     0]]))