**25.1<br>Run the Floyd-Warshall algorithm on the weighted, directed graph of Figure 25.2. Show the matrix $D^{(k)}$ that results for each iteration of the outer loop.**

In [25]:
def floyd_warshall(W):
    n=len(W)
    # D is a collection of D(i), i=0,1,2,...,k
    D=[W] # D(i) is a list of n*n matrices.
    for k in range(n):
        # generate an empty n*n matrix D(k) for each k
        # append D(k) to D
        D.append(W)
        for i in range(n):
            for j in range(n):
                # modify the value of every cell dij in D(k)
                # according to optimal substructure
                D[k+1][i][j]=min(D[k][i][j],D[k][i][k]+D[k][k][j])
        print (D[k],'\n')
    # the final solution of dij is the last D(n) added to D
    return D[n]

In [26]:
W=[[0,10000,10000,10000,-1,10000],
  [1,0,10000,2,10000,10000],
  [10000,2,0,10000,10000,-8],
  [-4,10000,10000,0,3,10000],
  [10000,7,10000,10000,0,10000],
  [10000,5,10,10000,10000,0]]
floyd_warshall(W)

[[0, 10000, 10000, 10000, -1, 10000], [1, 0, 10000, 2, 0, 10000], [10000, 2, 0, 10000, 9999, -8], [-4, 9996, 9996, 0, -5, 9996], [10000, 7, 10000, 10000, 0, 10000], [10000, 5, 10, 10000, 9999, 0]] 

[[0, 10000, 10000, 10000, -1, 10000], [1, 0, 10000, 2, 0, 10000], [3, 2, 0, 4, 2, -8], [-4, 9996, 9996, 0, -5, 9996], [8, 7, 10000, 9, 0, 10000], [6, 5, 10, 7, 5, 0]] 

[[0, 10000, 10000, 10000, -1, 9992], [1, 0, 10000, 2, 0, 9992], [3, 2, 0, 4, 2, -8], [-4, 9996, 9996, 0, -5, 9988], [8, 7, 10000, 9, 0, 9992], [6, 5, 10, 7, 5, 0]] 

[[0, 10000, 10000, 10000, -1, 9992], [-2, 0, 9998, 2, -3, 9990], [0, 2, 0, 4, -1, -8], [-4, 9996, 9996, 0, -5, 9988], [5, 7, 10000, 9, 0, 9992], [3, 5, 10, 7, 2, 0]] 

[[0, 6, 9999, 8, -1, 9991], [-2, 0, 9997, 2, -3, 9989], [0, 2, 0, 4, -1, -8], [-4, 2, 9995, 0, -5, 9987], [5, 7, 10000, 9, 0, 9992], [3, 5, 10, 7, 2, 0]] 

[[0, 6, 9999, 8, -1, 9991], [-2, 0, 9997, 2, -3, 9989], [-5, -3, 0, -1, -6, -8], [-4, 2, 9995, 0, -5, 9987], [5, 7, 10000, 9, 0, 9992], [3, 5,

[[0, 6, 9999, 8, -1, 9991],
 [-2, 0, 9997, 2, -3, 9989],
 [-5, -3, 0, -1, -6, -8],
 [-4, 2, 9995, 0, -5, 9987],
 [5, 7, 10000, 9, 0, 9992],
 [3, 5, 10, 7, 2, 0]]

**25.2<br>Show how to compute the transitive closure using the technique of Section 25.1.**

In [33]:
#import numpy as np
def floyd_warshall_transitive_closure(W):
    n=len(W)
    # T is a collection of T(i), i=0,1,2,...,k
    T=[W]
    # define T0, which is a identity matrix + edges in W as 1
    for i in range(n):
        for j in range(n):
            if W[i][j]<10000:
                T[0][i][j]=1
            else:
                T[0][i][j]=0
    #print (T[0])
    for k in range(n):
        # generate an empty n*n matrix T(k) for each k
        # append T(k) to T to work on
        T.append(W)
        
        for i in range(n):
            for j in range(n):
                # modify the value of every cell tij in T(k)
                # according to optimal substructure
                T[k+1][i][j]=(T[k][i][j] or (T[k][i][k] and T[k][k][j]))
        
    # the final solution of dij is the last T(n) added to T
    return T[n]

In [34]:
W=[[0,10000,10000,10000,-1,10000],
  [1,0,10000,2,10000,10000],
  [10000,2,0,10000,10000,-8],
  [-4,10000,10000,0,3,10000],
  [10000,7,10000,10000,0,10000],
  [10000,5,10,10000,10000,0]]
floyd_warshall_transitive_closure(W)

[[1, 0, 0, 0, 1, 0], [1, 1, 0, 1, 0, 0], [0, 1, 1, 0, 0, 1], [1, 0, 0, 1, 1, 0], [0, 1, 0, 0, 1, 0], [0, 1, 1, 0, 0, 1]]


[[1, 1, 0, 1, 1, 0],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 1, 1, 1, 1],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 1, 1, 1, 1]]

**25.2-3<br>Modify the FLOYD-WARSHALL procedure to compute the $\Pi ^{(k)}$ matrices according to equations (25.6) and (25.7). Prove rigorously that for all $i\in V$, the predecessor subgraph $G_{\pi ,i}$ is a shortest path tree with root $i$. (*Hint*: To show that $G_{\pi ,i}$ is acyclic, first show that $\pi _{ij}^{(k)}=l$ implies $d_{ij}^{(k)} \geq d_{il}^{(k)}+w_{ij}$, according to the definition of $\pi _{ij}^{(k)}$. Then, adapt the proof of Lemma 24.16.)**

In [41]:
import numpy as np
def floyd_warshall_predecessor_subgraph(W):
    
    n=len(W)
    # define D0
    D=[W]
    
    # define P0 according to equation 25.6
    P=[np.zeros((n,n))]
    for i in range(n):
        for j in range(n):
            if W[i][j]<10000 and W[i][j]!=0:
                P[0][i][j]=i
            else:
                P[0][i][j]=np.nan
    
    for k in range(n):
        # generate an empty n*n matrix for each k to work on
        P.append(np.zeros((n,n)))
        
        D.append(np.zeros((n,n)))
        
        for i in range(n):
            for j in range(n):
                
                # assign value of P[k] according to equation 25.7
                if D[k][i][j]<=D[k][i][k]+D[k][k][j]:
                    P[k+1][i][j]=P[k][i][j]
                else:
                    P[k+1][i][j]=P[k][k][j]
                # modify the value of every cell dij in D(k)
                D[k+1][i][j]=min(D[k][i][j],D[k][i][k]+D[k][k][j])
        #print (k,P[k])
                       
    # the final solution of P and D is the last matrice (n) 
    return P[n], D[n]

In [42]:
# for line 27 to work properly, entry of W has to be np.inf, 10000 will not work any more
W_=np.array([[0,np.inf,np.inf,np.inf,-1,np.inf],
  [1,0,np.inf,2,np.inf,np.inf],
  [np.inf,2,0,np.inf,np.inf,-8],
  [-4,np.inf,np.inf,0,3,np.inf],
  [np.inf,7,np.inf,np.inf,0,np.inf],
  [np.inf,5,10,np.inf,np.inf,0]])
floyd_warshall_predecessor_subgraph(W_)

(array([[nan,  4., nan,  1.,  0., nan],
        [ 3., nan, nan,  1.,  0., nan],
        [ 3.,  5., nan,  1.,  0.,  2.],
        [ 3.,  4., nan, nan,  0., nan],
        [ 3.,  4., nan,  1., nan, nan],
        [ 3.,  5.,  5.,  1.,  0., nan]]),
 array([[ 0.,  6., inf,  8., -1., inf],
        [-2.,  0., inf,  2., -3., inf],
        [-5., -3.,  0., -1., -6., -8.],
        [-4.,  2., inf,  0., -5., inf],
        [ 5.,  7., inf,  9.,  0., inf],
        [ 3.,  5., 10.,  7.,  2.,  0.]]))

**25.2-4<br>As it appears above, the Floyd-Warshall algorithm requires $\Theta (n^3)$ space, since we compute $d_{ij}^{(k)}$ for $i,j,k=1,2,...n$. Show that the following procedure, which simply drops all the superscripts, is correct, and thus only $\Theta (n^2)$ space is required.**
```
FLOYD-WARSHALL'(W)
1 n=W.rows
2 D=W
3 for k=1 to n
4     for i=1 to n
5         for j=1 to n
6             dij=min(dij,dik+dkj)
7 return D
```

Proof: on line 6, we are gradually updating the $(i,j)$ entry of $D$. The new value depends on the old value of three entries $(i,j)$, $(i,k)$ and $(k,j)$. For the $i*j$ times we update $D$ for a certain $k$, we look at $(i,j)$, $(i,k)$ and $(k,j)$ exactly once. Therefore we only have to prove that $(i,k)$ and $(k,j)$ entries will not be affected by update:
* For $i\neq k$ and $j\neq k$, it is apparent, because only $(i,j)$ entry is updated
* For $i=k$ or $j=k$, we know $d_{ij}^{(k)}=d_{ij}^{(k-1)}$, because $k$ cannot be the end of path and an intermediate in the path *at the same time*.

Combining the two cases, we conclude that $(i,k)$ and $(k,j)$  are not changed for every $k$, the correctness of the algorithm is proved. 

Running the following `floyd_warshall_n2` on $W$ returns the same answer as `floyd_warshall`:

In [3]:
def floyd_warshall_n2(W):
    n=len(W)
    D=W.copy() # build D based on W
    for k in range(n):
        for i in range(n):
            for j in range(n):
                # modify the value of every cell dij in D
                # according to optimal substructure
                D[i][j]=min(D[i][j],D[i][k]+D[k][j])
   
    return D

In [4]:
W=np.array([[0,10000,10000,10000,-1,10000],
  [1,0,10000,2,10000,10000],
  [10000,2,0,10000,10000,-8],
  [-4,10000,10000,0,3,10000],
  [10000,7,10000,10000,0,10000],
  [10000,5,10,10000,10000,0]])
floyd_warshall_n2(W)

array([[    0,     6,  9999,     8,    -1,  9991],
       [   -2,     0,  9997,     2,    -3,  9989],
       [   -5,    -3,     0,    -1,    -6,    -8],
       [   -4,     2,  9995,     0,    -5,  9987],
       [    5,     7, 10000,     9,     0,  9992],
       [    3,     5,    10,     7,     2,     0]])

**24.2-5<br>Suppose that we modify the way in which equation (25.7) handles equality:**

$$
\begin{align}
\pi _{ij}^{(k)}=\left\{
        \begin{array}{ll}
        \pi _{ij}^{(k-1)} &\text{if}\ d_{ij}^{(k-1)}<d_{ik}^{(k-1)}+d_{kj}^{(k-1)}\\
        \pi _{kj}^{(k-1)} &\text{if}\ d_{ij}^{(k-1)} \geq d_{ik}^{(k-1)}+d_{kj}^{(k-1)}\\
        \end{array}
        \right.
\end{align}
$$

**Is this alternative definition of the predecessor matrix $\Pi$ correct?**

It is correct, it will return alternative shortest paths, which are not unique. (On the other hand, the shortest path weights matrix $D$ is unique, it is not affected here.)

**25.2-6<br>How can we use the output of the Floyd-Warshall algorithm to detect the presence of a negative-weight cycle?**

If negative cycles exists between $i$ to $j$ through the intermediate vertex $k$, then we have the condition $d_{ik}+d_{kj}+d_{ji}<0$. We can check it under the nested `for` loop, before we start updating the values in $D^{(k)}$.

In [31]:
def floyd_warshall_n2_negative_cycle(W):
    n=len(W)
    D=W.copy() # build D based on W
    for k in range(n):
        for i in range(n):
            for j in range(n):
                # check existence of negative-weight cycle
                # before update with for D(k)
                if D[i][k]+D[k][j]+D[j][i]<0:
                    return False
                D[i][j]=min(D[i][j],D[i][k]+D[k][j])
    return True

In [29]:
# Running on W from Figure 25.2, which contains no negative-weight cycles
W=np.array([[0,10000,10000,10000,-1,10000],
  [1,0,10000,2,10000,10000],
  [10000,2,0,10000,10000,-8],
  [-4,10000,10000,0,3,10000],
  [10000,7,10000,10000,0,10000],
  [10000,5,10,10000,10000,0]])
floyd_warshall_n2_negative_cycle(W)

array([[    0,     6,  9999,     8,    -1,  9991],
       [   -2,     0,  9997,     2,    -3,  9989],
       [   -5,    -3,     0,    -1,    -6,    -8],
       [   -4,     2,  9995,     0,    -5,  9987],
       [    5,     7, 10000,     9,     0,  9992],
       [    3,     5,    10,     7,     2,     0]])

In [32]:
# Running on W_, which is a simple negative-weight cycle
W_=np.array([[0,1,10000],
           [10000,0,2],
           [-4,10000,0]])
floyd_warshall_n2_negative_cycle(W_)

False

**25.2-7<br>Another way to reconstruct shortest paths in the Floyd-Warshall algorithm uses values $\phi _{ij}^{(k)}$  for $i, j, k=1,2,...,n$, where $\phi _{ij}^{(k)}$ is the highest-numbered intermediate vertex of a shortest path from $i$ to $j$ in which all intermediate vertices are in the set $\{1,2,...,k\}$. Give a recursive formulation for $\phi _{ij}^{(k)}$, modify the FLOYD-WARSHALL procedure to compute the $\phi _{ij}^{(k)}$ values, and rewrite the PRINT-ALL- PAIRS-SHORTEST-PATH procedure to take the matrix $\Phi =\phi _{ij}^{(n)}$ as an input. How is the matrix $\Phi$ like the $s$ table in the matrix-chain multiplication problem of Section 15.2?**

The `floyd_warshall_shortestpath` procedure computes $\Phi =\phi _{ij}^{(n)}$. The `print_apsp` procedure prints the shortest path between two given vertices. It is similar to the PRINT-OPTIMAL-PARENS procedure on page 377, that an intermediate $\phi _{ij}$ value splits the solution into two. We can determine the solution recursively until we found no intermediate vertex, i.e. $\phi _{ij}=-1$.

In [102]:
import numpy as np
def floyd_warshall_shortestpath(W):
    
    n=len(W)
    # define D0
    D=W.copy()
    
    # initiation P0: intermediate vertices drawn from an empty set {}
    # entries on principle axis is np.nan (i.e no path from i to i)
    # entries when W[i,j]=inf is np.nan -> no intermediate vertices at initiation
    # entries when W[i,j]!=inf means path from i to j without intermediates
    # -> it fulfils the definition
    # -> to distinguish them from vertex 0 (Python index starts from 0),
    # -> P[i,j] is assigned as -1
    P=[np.zeros((n,n))]
    for i in range(n):
        for j in range(n):
            if i==j or W[i][j]==np.inf:
                P[0][i][j]=np.nan
            else:
                P[0][i][j]=-1
    
    #print (P[0])
    
    for k in range(n):
        # generate an empty n*n matrix for each k to work on
        P.append(np.zeros((n,n)))
        
        for i in range(n):
            for j in range(n):
                
                # k is NOT an intermediate, keep the old value
                if D[i][j]<=D[i][k]+D[k][j]:
                    P[k+1][i][j]=P[k][i][j]
                else: # if k is an intermediate, then take the value of k
                    P[k+1][i][j]=k
                # modify the value of every cell dij in D(k)
                D[i][j]=min(D[i][j],D[i][k]+D[k][j])
                                    
    # the final solution of P is the last matrice (n) 
    return P[n]

def print_apsp(P,i,j):
    # end of solution, no intermediate, i->j is a direct path
    if P[int(i)][int(j)]==-1:
        print (int(i))
    elif P[int(i)][int(j)]==np.nan:
        print ('no path from',i,'to','j')
    else:
        # P[i,j] splits the solution into two
        print_apsp(P,i,P[int(i)][int(j)])
        print_apsp(P,P[int(i)][int(j)],j)


In [103]:
W_=np.array([[0,np.inf,np.inf,np.inf,-1,np.inf],
  [1,0,np.inf,2,np.inf,np.inf],
  [np.inf,2,0,np.inf,np.inf,-8],
  [-4,np.inf,np.inf,0,3,np.inf],
  [np.inf,7,np.inf,np.inf,0,np.inf],
  [np.inf,5,10,np.inf,np.inf,0]])
# calculate the Phi matrix of W_
Phi=floyd_warshall_shortestpath(W_)
# print APSP for any vertex pair in Phi
print_apsp(Phi,2,0)

2
5
1
3


**25.2-8<br>Give an $O(VE)$-time algorithm for computing the transitive closure of a directed graph $G=(V,E)$.**

In [5]:
#import numpy as np
def floyd_warshall_transitive_closure_VE(W):
    n=len(W)
    # T is a collection of T(i), i=0,1,2,...,k
    T=[W]
    opened={}
    closed={}
    # define T0, which is a identity matrix + edges in W as 1
    for i in range(n):
        for j in range(n):
            if W[i][j]<10000:
                T[0][i][j]=1
                opened[str(i)+str(j)]=1
            else:
                T[0][i][j]=0
                closed[str(i)+str(j)]=0
    print (opened)
    print (closed)
    for k in range(n):
        # generate an empty n*n matrix T(k) for each k
        # append T(k) to T to work on
        T.append(W)
        for i in closed:
            pass
            
       
                # modify the value of every cell tij in T(k)
                # according to optimal substructure
            #T[k+1][i][j]=(T[k][i][k] and T[k][k][j]))
        
    # the final solution of dij is the last T(n) added to T
    return T[n]

{'00': 1, '04': 1, '10': 1, '11': 1, '13': 1, '21': 1, '22': 1, '25': 1, '30': 1, '33': 1, '34': 1, '41': 1, '44': 1, '51': 1, '52': 1, '55': 1}
{'01': 0, '02': 0, '03': 0, '05': 0, '12': 0, '14': 0, '15': 0, '20': 0, '23': 0, '24': 0, '31': 0, '32': 0, '35': 0, '40': 0, '42': 0, '43': 0, '45': 0, '50': 0, '53': 0, '54': 0}


array([[1, 0, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [1, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1]])